Horizontal Stepper Component
jflavio1/DaggerTraining pull request #15
Opened 2019-02-14 17:27 UTC by enzoftware

Desarrollo del componente 'horizontal stepper' 
### Fix
- Reset

2019-02-14 20:04 UTC, jflavio11 requested changes
Colocar comentarios, pls

2019-02-14 21:40 UTC, enzoftware commented
Mas tarde empiezo a comentar todas las funcionalidades :+1:

2019-02-15 16:51 UTC, jflavio1 commented on app/src/main/java/com/jflavio1/daggerexample/core/components/stepper/NavigationBar.java
> +     * I don't know what happens here xd
XD

2019-02-15 16:51 UTC, jflavio1 commented on app/src/main/java/com/jflavio1/daggerexample/core/components/stepper/NavigationBar.java
> +     * Draw in the screen teh foreground and background colors and the points
No olvidar colocar punto final

2019-02-15 16:52 UTC, jflavio1 commented on app/src/main/java/com/jflavio1/daggerexample/core/components/stepper/NavigationBar.java
> +     * @param canvas The canvas
Aquí también colocar punto final y una separación entre la descripción del método y la declaración de parámetros

2019-02-15 16:53 UTC, jflavio11 approved these changes
Revisar comentarios

2019-02-15 16:55 UTC, enzoftware commented on app/src/main/java/com/jflavio1/daggerexample/core/components/stepper/NavigationBar.java
> +     * I don't know what happens here xd
:'v

2019-02-15 16:56 UTC, jflavio1 commented
FYI
[https://source.android.com/setup/contribute/code-style](url)
[https://google.github.io/styleguide/javaguide.html](url)

2019-02-15 16:59 UTC, enzoftware commented on app/src/main/java/com/jflavio1/daggerexample/core/components/stepper/NavigationBar.java
> +     * @param canvas The canvas
:ballot_box_with_check:

2019-02-15 19:29 UTC, merged